### ISSUE TITLE
Need Some One to Update Readme.md file for the Chenethasantha folder

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#11]
Need to install the Application reg it and should document the process and also should document the steps as well reg it.

**Comment by jhhornn** [comment]
Do you mean the overall process of setting up the application directly on my local computer?

**Comment by manjunani** [comment]
Hi @jhhornn  Yes.

**Comment by jhhornn** [comment]
Hello @manjunani 
Okay then, seems some of the processes have been included in the individual folder's readme, so I'd just help with compiling everything in the overall folder.
If it's as I described above, should I go ahead?

**Comment by manjunani** [comment]
yeah you can proceed further in making the changes in the chenethasantha folder's readme file

**Comment by jhhornn** [comment]
Was able to help with it in my little way [18](https://github.com/Xtreme-Thinkers/hacktoberfest2022/pull/18)
