### ISSUE TITLE
Need someone to document the process of tax calculation into the readme file

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#16]

**Comment by manjunani** [comment]
you should for the repo and add the doumentation onto readme file in tax-calculator folder

**Comment by Shamik1836** [comment]
Can I work on this issue @manjunani ?

**Comment by Shamik1836** [comment]
And one thing, is this for India only or globally?

**Comment by Vedant755** [comment]
Hey! Can I work on this I have completed 2 assignments on readme this 5 days! I will do it well!

**Comment by manjunani** [comment]
Hi @Shamik1836 , you can work on this.. and this thing is for global not restricted to india only
