### ISSUE TITLE
Enhance Find Password in password Manage folder

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#2]
Hey There,
I am currently Looking for contributions on my Password Manager
Please do Clone the Repo first and then work on the feature enhancement.

Requirements -
we should be able to find the password based on the first_name and last_name and key char
first_name and last_name should be used to get the respective json 
and when we get that respective json file we should be able to search in that particular file with the key char

**Comment by Montekkundan** [comment]
Hi can you assign it to me! 😄

**Comment by manjunani** [comment]
Sorry buddy, let others work on this.... and other issues i had assigned the enhancement of main function (generate_password()) on your name. it is the heart of our code....

**Comment by manjunani** [comment]
hi @Montekkundan , Please go ahead with your changes

**Comment by Montekkundan** [comment]
@manjunani Thank you 😄

**Comment by manjunani** [comment]
Hey @Montekkundan , any Update on the development ?

**Comment by Montekkundan** [comment]
@manjunani hi will send pr by today for all
