### ISSUE TITLE
Enhance the Update Password in password manager

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#3]
Hey There,
I am currently Looking for contributions on my Password Manager
Please do Clone the Repo first and then work on the feature enhancement.

Requirements -
we should be able to find the password based on the first_name and last_name and key char
first_name and last_name should be used to get the respective json
and when we get that respective json file we should be able to search in that particular file with the key char and based one key char we should update the password

**Comment by manjunani** [comment]
do let me know if you need some more info

**Comment by Montekkundan** [comment]
Hi can you assign it to me! 😄

**Comment by manjunani** [comment]
Hi @Montekkundan, Please go ahead with your changes

**Comment by Montekkundan** [comment]
@manjunani I wanted to ask as you merged my pr will it count in hacktoberfest? 
If not could you rather merge my next pr's after the hacktoberfest officially starts! Thanks

**Comment by manjunani** [comment]
sorry bud, i hope as the hacktoberfest starts from october the pr's might count from that .
@Montekkundan  anyway i will raise other bunch of issues in this repo for other to contribute as well..you can contribute in them and can raise PR as well..

or you can raise pr to any other repo other than this on the github/gitlab which will be counted to hacktoberfest 2022

**Comment by manjunani** [comment]
hi @Montekkundan any update on the development part for this issue?

**Comment by Montekkundan** [comment]
@manjunani hello will update by tomorrow, i have few assignments to do. Thank you
