### ISSUE TITLE
Need some to fix the typos on main readme file and correct the code for getting all the contributors images

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#30]

**Comment by devBayo** [comment]
Kindly assign to me

**Comment by manjunani** [comment]
hey buddy, try to work on the changes and raise the PR once the issue is assigned on to your name

**Comment by devBayo** [comment]
I've worked on the typos, you can close the issue.

**Comment by manjunani** [comment]
The issue has been resolved and the readme has been updated
