### ISSUE TITLE
Need some fix in the Drawing App

### ISSUE THREAD

**Issue by saikatdgp2001** [Xtreme-Thinkers/hacktoberfest2022#33]
Fixes in the Drawing App are:-
-Adding a dynamic slider for the Eraser and Pen size 
-Adding background color feature
-Adding some UI changes to make it more interactive

**Comment by saikatdgp2001** [comment]
please kindly review the issue and assign me

**Comment by manjunani** [comment]
@saikatdgp2001 , sure please go ahead

**Comment by saikatdgp2001** [comment]
@manjunani, the Issue is fixed kindly review it, and please merge it with the proper tags.

**Comment by manjunani** [comment]
can u include the respective readme file along with the respective screens and their usage and all

**Comment by saikatdgp2001** [comment]
Sure

SAIKAT DAS

**Comment by manjunani** [comment]
PR Merged to the main
