### ISSUE TITLE
Need a working calculator using HTML , CSS and Javascript

### ISSUE THREAD

**Issue by AmitSharma512** [Xtreme-Thinkers/hacktoberfest2022#40]

**Comment by AmitSharma512** [comment]
plz assign it to me

**Comment by vilasrhegde** [comment]
@manjunani  can you assign me?

**Comment by vilasrhegde** [comment]
Hey @manjunani can you proceed with my PR? Thanks

**Comment by manjunani** [comment]
Sorry @vilasrhegde, the issue has been already resolved, i forgot to close the issue. and i can see there was no PR raised by u under this repo..do check again and if you intended to work get the issue assigned on your name and work on it and the raise the PR
