### ISSUE TITLE
Need some one to add readme file documentation on the feedback app folder and update it.

### ISSUE THREAD

**Issue by manjunani** [Xtreme-Thinkers/hacktoberfest2022#44]

**Comment by sahil-rathi** [comment]
Can you please assign me this

**Comment by manjunani** [comment]
Hey @sahil-rathi , go ahead with the changes buddy

**Comment by sahil-rathi** [comment]
@manjunani the readme for feedback application has been updated , please kindly merge the pull request. Thanks

**Comment by manjunani** [comment]
@sahil-rathi , kindly update the readme with respective to the usage of the application so that others can take use of it .

i didn't intended to have my details on readme.
try installing the application and figure the things out and then update the readme..
if you find any bugs by the way raise them. so others can also work on them

**Comment by sahil-rathi** [comment]
The application was not starting so I thought that was what you meant.
Anyways I am working on it now.

**Comment by manjunani** [comment]
The issue is resolved
