### ISSUE TITLE
Want to add hangman game

### ISSUE THREAD

**Issue by Nithin-532** [Xtreme-Thinkers/hacktoberfest2022#55]
I want to add hangman game which is a basic python project(easy level). Basically hangman game based on guessing letter of a word or a word, in which we have 6 tries. After 6 failures the game will end and you can continue playing just like any other game.

**Comment by manjunani** [comment]
Hey @Nithin-532 , i appreciate your enthusiasm for the contribution to the open source but Sorry buddy as of now we are not accepting games as a part of contribution in this repo and the existing games will be prevailed once the hacktoberfest end 
try thinking of any different application and contribute reg it.
