### ISSUE TITLE
Tic-Tac-Toe

### ISSUE THREAD

**Issue by ishubham010** [Xtreme-Thinkers/hacktoberfest2022#63]
Hello, I want to contribute Tic Tac Toe Game.

**Comment by KaxitPandya** [comment]
@ishubham010 @manjunani  I have created Tic Tac Toe, Please accept my pull request

**Comment by manjunani** [comment]
Hey @ishubham010 @KaxitPandya , I appreciate your enthusiasm for contributing to this open source repo but as of now we are not accepting any games as a part of contribution on this repo.
kindly try creating some applications with some frameworks /libraries etc., and the existing game application that you might be seeing will be removed as well.
and if you guys intended to contribute try creating the issue first and then get it assigned on your name and then make changes and then raise a pr to get it merged

**Comment by ishubham010** [comment]
Dear Admin, please mention the name correctly who is not following rules and regulations. 
@KaxitPandya try to raise your own issue and kindly don't contribute to the work if it is not assigned to you. Atleast wait for admin reply.
