### ISSUE TITLE
Some Changes in Design Using hover and etc.

### ISSUE THREAD

**Issue by dvig14** [Xtreme-Thinkers/hacktoberfest2022#8]
Can u assign me this issue. with hacktoberfest 2022 label

**Comment by manjunani** [comment]
can u explain me what was the issue with the design and what was the problem that this changes gonna fix

**Comment by dvig14** [comment]
I can make changes using hover effect and text shadow, box shadow like when
u click on link it will has some effect on it like color change, text
change ....etc.

**Comment by manjunani** [comment]
Sorry  @dvig14 , is there any other thing or new feature you can come up with i don't think those changes are necessary for the repo. do contribute your  ideas in here in a form of new program or new idea or new project.

if you do feel that this issue that you mentioned above is the only one you can work on i am happy to assign you this issue.

**Comment by dvig14** [comment]
Hey, actually I create an issue to make changes in portfolio folder
(website).
And I don't have any other idea😊.

**Comment by manjunani** [comment]
Ok Then Go Ahead and make the changes .....

**Comment by manjunani** [comment]
Hey @dvig14  any update on the above changes that you mentioned?

**Comment by dvig14** [comment]
Hey, actually I am busy ,I will make changes in few days .....is it ok

**Comment by manjunani** [comment]
yep take your time
